### ISSUE TITLE
Zipfile not copied to working directory

### ISSUE THREAD

**Issue by skbormann** [dirtyhawk/stata-zippkg#1]
The created zipfile is not copied to the current working directory and instead is deleted during the removal of the temporal folder.
To fix this issue I added a copy command after the call to zipfile 
> ``q'  zipfile `"`archivetargets'"' , saving(`"`saving'"') 

in  line 214, so that the new line 215 looks like

 >copy `"`archivebase'/`saving'"' `"`oldpwd'/`saving'"', `replace' 

The code may not look correctly in markdown, but I could not figure out how to format the code and still keep the Stata macro expansion intact. But the code should show where the problem lies and how to fix it.

**Comment by dirtyhawk** [comment]
Hi @skbormann ,

for some reason, I didn't get notified when you posted this issue. Sorry! The very same issue was brought to my attention just today; it only happens when you use relative file paths for the target file name – and the default (if no `saving` option is specified) is to use the relative file path `zippkg.zip`. I didn't see this problem earlier, because I usually use absolute file paths in the first place. My bad.

This has been fixed with an internal path conversion helper in the [current release 1.1](https://github.com/dirtyhawk/stata-zippkg/releases/tag/v1.1). I chose to go a slightly different path than you suggested, although your workaround also is a valid solution of course. Thanks for reporting it.

Now I have to look into my Github notification settings, it seems.

All the best
Bela
